# Generated by Django 6.0.6 on 2026-06-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_name',
        ),
        migrations.AddField(
            model_name='services',
            name='active',
            field=models.BooleanField(default=False, verbose_name='¿Está Activo?'),
        ),
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Color Hexadecimal (Ej: #28a745)'),
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clase del Icono (Opcional)'),
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(default='No name', max_length=100, verbose_name='Nombre del Servicio'),
        ),
        migrations.AddField(
            model_name='services',
            name='url_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de la URL (name)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
