# Generated by Django 5.1.15 on 2026-06-30 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (cm)')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('activity_factor', models.DecimalField(choices=[(1.2, 'Sedentario (poco o ningún ejercicio)'), (1.375, 'Ligero (1-3 días/semana)'), (1.55, 'Moderado (3-5 días/semana)'), (1.725, 'Activo (6-7 días/semana)'), (1.9, 'Muy activo (ejercicio intenso diario)')], decimal_places=2, max_digits=3, verbose_name='Factor de actividad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
