# Generated by Django 5.1.15 on 2026-06-30 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_healthprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='activity_factor',
            field=models.DecimalField(choices=[(Decimal('1.200'), 'Sedentario (poco o ningún ejercicio)'), (Decimal('1.375'), 'Ligero (1-3 días/semana)'), (Decimal('1.550'), 'Moderado (3-5 días/semana)'), (Decimal('1.725'), 'Activo (6-7 días/semana)'), (Decimal('1.900'), 'Muy activo (ejercicio intenso diario)')], decimal_places=3, max_digits=4, verbose_name='Factor de actividad'),
        ),
    ]
